## K nearest neighbor is a lazy learning model. We do not build a model at all. This is a non parametric model, so no parametres are needed to be calculated. FOr less features, we use euclidean distance. For more features, we use manhattan distance.

## If K is too small, outlier has a huge impact on the model. This causes overfitting.

## If k is too large, it causes underfitting. Because, the classifier predicts the majority class regardless of which neighnbors are nearest.


In [13]:
import numpy as np
from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import pandas as pd
from sklearn.model_selection import cross_val_score, cross_validate

In [14]:
data = pd.read_csv('/content/credit_data.csv')
features = data[['income', 'age', 'loan']]
target = data.default

In [15]:
X = np.array(features).reshape(-1,3)
y = np.array(target)

In [16]:
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [17]:
y

array([0, 0, 0, ..., 1, 0, 0])

## We will do Mini Max Normalization on the X. For KNN, Min Max normalization works well.

In [18]:
X = preprocessing.MinMaxScaler().fit_transform(X)
X

array([[0.9231759 , 0.89209175, 0.58883739],
       [0.28812165, 0.65470788, 0.47682695],
       [0.74633429, 0.9811888 , 0.58262011],
       ...,
       [0.48612202, 0.21695807, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.82970913, 0.53597028]])

In [19]:
trainX, testX, trainY, testY = train_test_split(X, y, test_size=0.3)

model = KNeighborsClassifier(n_neighbors=20)

model.fit(trainX, trainY)

predicted = model.predict(testX)


In [20]:
confusion_matrix(testY, predicted)

array([[508,   4],
       [ 15,  73]])

In [21]:
accuracy_score(testY, predicted)

0.9683333333333334

## The accuracy is high because we used Mini Max transformation. If we did not use mini max transfornmation, our accuracy would have been somewhere near 85%.

In [22]:
cross_valid_scores = []
for k in range(1,100):
  knn = KNeighborsClassifier(n_neighbors = k)
  scores = cross_val_score(knn, X, y, cv = 10, scoring = 'accuracy')
  cross_valid_scores.append(scores.mean())

print('Optimal K with cross-validation: ', np.argmax(cross_valid_scores))


Optimal K with cross-validation:  32


In [23]:
trainX, testX, trainY, testY = train_test_split(X, y, test_size=0.3)

model = KNeighborsClassifier(n_neighbors=32)

model.fit(trainX, trainY)

predicted = model.predict(testX)

confusion_matrix(testY, predicted)
accuracy_score(testY, predicted)

0.9683333333333334