In [3]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

data = pd.read_csv('/content/credit_data.csv')

features = data[['income', 'age', 'loan']]

target = data.default

trainX, testX, trainY, testY = train_test_split(features, target, test_size=0.3)

In [4]:
features.corr()


income       age      loan
income  1.000000 -0.034984  0.441117
age    -0.034984  1.000000  0.006561
loan    0.441117  0.006561  1.000000

In [6]:

model = GaussianNB()
model.fit(trainX, trainY)
predictions = model.predict(testX)




In [7]:
confusion_matrix(testY, predictions)


array([[508,  10],
       [ 29,  53]])

In [8]:
accuracy_score(testY, predictions)

0.935

# Text Clustering with Naive Bayes

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()

tfidf = vec.fit_transform(['I like Machine Learning',
                          'Aplle, Oranges and other fruits are healthy',
                          'Is it feasible with machinhe learning algorithms?',
                          'My family is happy because of the healthy fruits.'])

print(tfidf)

  (0, 12)	0.48693426407352264
  (0, 14)	0.6176143709756019
  (0, 13)	0.6176143709756019
  (1, 9)	0.3155366632994909
  (1, 3)	0.4002182475169386
  (1, 7)	0.3155366632994909
  (1, 19)	0.4002182475169386
  (1, 1)	0.4002182475169386
  (1, 18)	0.4002182475169386
  (1, 2)	0.4002182475169386
  (2, 0)	0.4002182475169386
  (2, 15)	0.4002182475169386
  (2, 21)	0.4002182475169386
  (2, 6)	0.4002182475169386
  (2, 11)	0.4002182475169386
  (2, 10)	0.3155366632994909
  (2, 12)	0.3155366632994909
  (3, 20)	0.3565798233381452
  (3, 17)	0.3565798233381452
  (3, 4)	0.3565798233381452
  (3, 8)	0.3565798233381452
  (3, 5)	0.3565798233381452
  (3, 16)	0.3565798233381452
  (3, 10)	0.2811316284405006
  (3, 9)	0.2811316284405006
  (3, 7)	0.2811316284405006


In [2]:
tfidf.A

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.48693426, 0.61761437, 0.61761437,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.40021825, 0.40021825, 0.40021825, 0.        ,
        0.        , 0.        , 0.31553666, 0.        , 0.31553666,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.40021825, 0.40021825,
        0.        , 0.        ],
       [0.40021825, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40021825, 0.        , 0.        , 0.        ,
        0.31553666, 0.40021825, 0.31553666, 0.        , 0.        ,
        0.40021825, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.40021825],
       [0.        , 0.        , 0.        , 0.        , 0.35657982,
        0.3565798

In [3]:
(tfidf*tfidf.T).A

array([[1.        , 0.        , 0.15364561, 0.        ],
       [0.        , 1.        , 0.        , 0.17741467],
       [0.15364561, 0.        , 1.        , 0.08870734],
       [0.        , 0.17741467, 0.08870734, 1.        ]])

# Text Classification with dataset

In [11]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

categories = ['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']
training_data = fetch_20newsgroups(subset = 'train', categories = categories, shuffle = True, random_state= 3)

training_data


{'data': ['From: geb@cs.pitt.edu (Gordon Banks)\nSubject: Re: My New Diet --> IT WORKS GREAT !!!!\nReply-To: geb@cs.pitt.edu (Gordon Banks)\nOrganization: Univ. of Pittsburgh Computer Science\nLines: 35\n\nIn article <1993Apr22.001642.9186@omen.UUCP> caf@omen.UUCP (Chuck Forsberg WA7KGX) writes:\n\n>>>>Can you provide a reference to substantiate that gaining back\n>>>>the lost weight does not constitute "weight rebound" until it\n>>>>exceeds the starting weight?  Or is this oral tradition that\n>>>>is shared only among you obesity researchers?\n>>>\n>>>Annals of NY Acad. Sci. 1987\n>>>\n>>Hmmm. These don\'t look like references to me. Is passive-aggressive\n>>behavior associated with weight rebound? :-)\n>\n>I purposefully left off the page numbers to encourage the reader to\n>study the volumes mentioned, and benefit therefrom.\n>\n\nGood story, Chuck, but it won\'t wash.  I have read the NY Acad Sci\none (and have it).  This AM I couldn\'t find any reference to\n"weight rebound".  I\'

## We are printing the first 10 line of the first data.

In [12]:
print('\n'.join(training_data.data[0].split('\n')[:10]))

From: geb@cs.pitt.edu (Gordon Banks)
Subject: Re: My New Diet --> IT WORKS GREAT !!!!
Reply-To: geb@cs.pitt.edu (Gordon Banks)
Organization: Univ. of Pittsburgh Computer Science
Lines: 35

In article <1993Apr22.001642.9186@omen.UUCP> caf@omen.UUCP (Chuck Forsberg WA7KGX) writes:

>>>>Can you provide a reference to substantiate that gaining back
>>>>the lost weight does not constitute "weight rebound" until it


## Now we will print thr target value of the first data

In [13]:
print('Target is:', training_data.target_names[training_data.target[0]])

Target is: sci.med


## Similarly, for the 2nd data

In [14]:
print('\n'.join(training_data.data[1].split('\n')[:10]))
print('Target is:', training_data.target_names[training_data.target[1]])

From: REXLEX@fnal.fnal.gov
Subject: Re: Hell_2:  Black Sabbath
Organization: FNAL/AD/Net
Lines: 20

In article <Apr.21.03.25.03.1993.1292@geneva.rutgers.edu>
salaris@niblick.ecn.purdue.edu (Rrrrrrrrrrrrrrrabbits) writes:

>I like those lyrics,
>since whenever I am approached by judgemental, pharisitical,
Target is: soc.religion.christian


## Now, we will train the text data and try to find out the target values of the texts.

### At first, we will tokenize the sentences.

#### For example,

I love Machine Learning.
I don't like Biology.

### After tokenizing. the first sentence is,
I - 1
love - 1
Machine - 1
Learning - 1
don't - 0
like - 0,
Biology - 0

## By using count_vector.vocabulary_ we can count the nummber of occurences of each word. In this case, the most used word is from.

In [34]:
count_vector = CountVectorizer()
x_train_counts = count_vector.fit_transform(training_data.data)
print(count_vector.vocabulary_)

{'from': 14887, 'geb': 15173, 'cs': 10324, 'pitt': 25234, 'edu': 12626, 'gordon': 15591, 'banks': 6140, 'subject': 31077, 're': 27031, 'my': 22541, 'new': 22922, 'diet': 11505, 'it': 18551, 'works': 35269, 'great': 15743, 'reply': 27664, 'to': 32493, 'organization': 23915, 'univ': 33581, 'of': 23610, 'pittsburgh': 25237, 'computer': 9338, 'science': 28897, 'lines': 20253, '35': 2038, 'in': 17556, 'article': 5529, '1993apr22': 1128, '001642': 17, '9186': 3287, 'omen': 23713, 'uucp': 33940, 'caf': 7670, 'chuck': 8599, 'forsberg': 14701, 'wa7kgx': 34572, 'writes': 35350, 'can': 7766, 'you': 35638, 'provide': 26355, 'reference': 27310, 'substantiate': 31127, 'that': 32139, 'gaining': 15051, 'back': 6024, 'the': 32142, 'lost': 20515, 'weight': 34836, 'does': 12051, 'not': 23250, 'constitute': 9622, 'rebound': 27125, 'until': 33738, 'exceeds': 13577, 'starting': 30664, 'or': 23870, 'is': 18474, 'this': 32270, 'oral': 23872, 'tradition': 32694, 'shared': 29429, 'only': 23757, 'among': 4911, '

In [38]:
x_train_counts

<2257x35788 sparse matrix of type '<class 'numpy.int64'>'
	with 365886 stored elements in Compressed Sparse Row format>

In [27]:
tfid_Transformer  = TfidfTransformer()
x_train_tfidf = tfid_Transformer.fit_transform(x_train_counts)
x_train_tfidf

<2257x35788 sparse matrix of type '<class 'numpy.float64'>'
	with 365886 stored elements in Compressed Sparse Row format>

In [28]:
model = MultinomialNB().fit(x_train_tfidf, training_data.target)

new = [' This has nothing to do with church of religion.', 'Software engineering is getting hotter']

x_new_counts = count_vector.transform(new)

x_new_tfidf = tfid_Transformer.transform(x_new_counts)

predicted = model.predict(x_new_tfidf)


for doc, category in zip(new, predicted):
  print('%r ------> %s' % (doc, training_data.target_names[category]))

' This has nothing to do with church of religion.' ------> soc.religion.christian
'Software engineering is getting hotter' ------> comp.graphics


In [31]:
predicted

array([3, 1])

In [32]:
categories

['alt.atheism', 'soc.religion.christian', 'comp.graphics', 'sci.med']

# While doing text classification with Naive Bayes, why do we train the model with the transformed TFIDF version?

### When training a text classification model, using the transformed TF-IDF version is beneficial for several reasons:

## Feature Representation: TF-IDF provides a more informative representation of the text data. It captures the importance of each term (word) within a document relative to its frequency across the entire corpus.
## Dimensionality Reduction: By transforming the raw text into TF-IDF vectors, we reduce the dimensionality of the feature space. This helps mitigate the curse of dimensionality and improves model efficiency.
## Weighting Rare Terms: TF-IDF assigns higher weights to terms that are rare across documents. Rare terms often carry more discriminative power for classification tasks.
## Noise Reduction: Common words (e.g., “the,” “and”) have low TF-IDF scores due to their high document frequency. By downweighting these terms, we reduce noise in the feature space.
## Naive Bayes Assumption: Naive Bayes assumes that features are conditionally independent given the class label. While this assumption is rarely met in practice, using TF-IDF helps mitigate dependencies by focusing on term importance rather than raw counts.
## In summary, training with transformed TF-IDF vectors enhances the model’s ability to capture relevant information and improve classification performance. 🚀 . If you have any more questions or need further clarification, feel free to ask!